name: Trigger auto deployment for azuredockersample

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/azuredockersample-AutoDeployTrigger-265d53c9-c230-4d66-bdb8-5b08fefb8c35.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREDOCKERSAMPLE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: azuresampleproject.azurecr.io
          registryUsername: ${{ secrets.AZUREDOCKERSAMPLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZUREDOCKERSAMPLE_REGISTRY_PASSWORD }}
          containerAppName: azuredockersample
          resourceGroup: azuredockersample
          imageToBuild: azuresampleproject.azurecr.io/azuredockersample:${{ github.sha }}
          dockerfilePath: Dockerfile

     

