name: Trigger auto deployment for azuresample

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Dockerfile/**'
    - '.github/workflows/azuresample-AutoDeployTrigger-5f026b32-e7ba-42f6-a104-80e326a4dafa.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURESAMPLE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}Dockerfile 
          registryUrl: azuresampleproject.azurecr.io
          registryUsername: ${{ secrets.AZURESAMPLE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURESAMPLE_REGISTRY_PASSWORD }}
          containerAppName: azuresample
          resourceGroup: AzureDeployment
          imageToBuild: azuresampleproject.azurecr.io/azuresample:${{ github.sha }}
          dockerfilePath: Dockerfile

     

