name: Trigger auto deployment for firstapplication

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/firstapplication-AutoDeployTrigger-c99cbb40-ead7-40de-a8ad-1ed445c15446.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.FIRSTAPPLICATION_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: firstapplication.azurecr.io
          registryUsername: ${{ secrets.FIRSTAPPLICATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FIRSTAPPLICATION_REGISTRY_PASSWORD }}
          containerAppName: firstapplication
          resourceGroup: AzureDeployment
          imageToBuild: firstapplication.azurecr.io/firstapplication:${{ github.sha }}
          dockerfilePath: Dockerfile

     

